# Generated by Django 2.0.6 on 2018-07-05 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180704_1201'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prestador',
            options={'verbose_name': 'Prestador', 'verbose_name_plural': 'Prestadores'},
        ),
        migrations.AddField(
            model_name='prestador',
            name='descripcion',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestador',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fechaCreación'),
        ),
        migrations.AlterField(
            model_name='prestador',
            name='foto_perfil',
            field=models.ImageField(upload_to='perfiles'),
        ),
    ]
