# Generated by Django 2.0.6 on 2018-07-05 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180705_1404'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prestador',
            old_name='skype',
            new_name='pagina_web',
        ),
    ]
